#name: DemoExecutor
#
#basic_auth:
#  username: 35cff40c-b4f8-4ca3-9217-d49c9c35f375
#  password: 03b774c9d260ad7329ad3c6dcbc6ea9bec943486
#

self_update: false

server_secret: master-secret

# for is running check during tests
secret: master-secret

sync_interval_pause_duration: 1 Second

trial_retention_duration: 30 Minutes

default_script_timeout: 3 Minutes

server_base_url: http://localhost:8888

nrepl:
  port: 7883
  bind: localhost
  enabled: false

http:
  host: localhost
  port: 8883
  ssl-port: 8443

reporter:
  max-retries: 10
  retry-factor-pause-duration: 3 Seconds

exec_user:
  name: NULL
  password: NULL

tmp_dir: 'tmp'

services:

  dispatcher:

    http:
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

windows:
  fsi_path: C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe


# WARNING: this section is a duplicate from the main project config
# to be kept in sync manually
constants:
  STATES:
    JOB:
      # custom order for the UI here, do not resort alphabetically!
      - passed
      - executing
      - pending
      - aborting
      - aborted
      - defective
      - failed
    TASK:
      - aborted
      - aborting
      - defective
      - executing
      - failed
      - passed
      - pending
    TRIAL:
      - aborted
      - aborting
      - defective
      - dispatching
      - executing
      - failed
      - passed
      - pending
    SCRIPT:
      - aborted
      - defective
      - executing
      - failed
      - passed
      - pending
      - skipped
      - waiting
    FINISHED:
      - aborted
      - defective
      - failed
      - passed
      - skipped
    IN_PROGRESS:
      - aborting
      - dispatching
      - executing
