nrepl:
  port: 7883
  bind: "127.0.0.1"
  enabled: true

http:
  host: localhost
  port: 8883
  ssl-port: 8443

name: DemoExecutor

basic_auth:
  username: DemoExecutor
  password: 5cfc3c91599a118ec0c67a6f2c15e7456cea71fa

reporter:
  max_retries: 1
  retry_ms_factor: 1000

exec_user:
  name: NULL
  password: NULL

sync_interval: 1.0

trial_retention_duration: 5 Minutes

tmp_dir: 'tmp'

# server_base_url: http://192.168.0.1:8882

services:

  dispatcher:

    http:
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

windows:
  fsi_path: C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe

